"""moon traced cell for cell from mock-sheet.png by trace_native.py — do not edit by hand."""

ROWS = [
    [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [None, None, None, None, None, None, None, None, (27, 2, 4), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [None, None, None, None, None, None, (31, 2, 1), (105, 8, 7), (117, 9, 8), (29, 3, 3), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, (99, 2, 6), None, None, None, None, None, None, None],
    [None, None, None, None, None, None, (105, 7, 5), (189, 14, 9), (42, 2, 2), (27, 5, 4), (24, 5, 5), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [None, None, None, None, None, (38, 0, 1), (183, 12, 8), (158, 14, 8), (53, 2, 3), (34, 4, 4), (24, 3, 4), (22, 6, 6), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [None, None, None, None, None, (36, 1, 2), (173, 14, 9), (196, 20, 12), (63, 3, 3), (38, 2, 3), (34, 4, 4), (23, 4, 4), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, (73, 4, 5), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [None, None, None, None, None, (42, 1, 2), (174, 11, 7), (173, 17, 11), (158, 14, 8), (60, 3, 4), (33, 1, 3), (35, 2, 2), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [None, None, None, None, None, (27, 2, 3), (36, 2, 2), (174, 16, 14), (184, 17, 13), (186, 18, 14), (164, 16, 13), (45, 2, 3), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, (81, 5, 8), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [(51, 1, 3), (35, 1, 2), None, None, None, (24, 5, 5), (31, 1, 3), (31, 0, 1), (43, 2, 3), (52, 2, 3), (34, 1, 1), (25, 4, 3), None, None, None, None, None, None, None, None, None, None, (105, 3, 5), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [(55, 3, 5), (46, 4, 5), (60, 4, 5), (29, 3, 3), None, None, (24, 4, 3), (25, 4, 3), (26, 4, 4), (24, 4, 4), (24, 6, 4), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [(55, 3, 5), (46, 4, 5), (60, 4, 5), (29, 3, 3), None, None, (24, 4, 3), (25, 4, 3), (26, 4, 4), (24, 4, 4), (24, 6, 4), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [(55, 3, 5), (46, 4, 5), (60, 4, 5), (29, 3, 3), None, None, (24, 4, 3), (25, 4, 3), (26, 4, 4), (24, 4, 4), (24, 6, 4), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [(30, 2, 2), (49, 3, 6), (64, 3, 4), (59, 3, 5), None, (22, 5, 5), None, (21, 5, 5), (19, 6, 5), None, None, None, None, None, None, (18, 6, 6), None, (23, 4, 4), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [None, None, None, (37, 1, 2), (54, 2, 2), (44, 1, 3), None, None, (19, 7, 6), (22, 7, 7), (22, 9, 7), (20, 7, 6), (19, 8, 7), None, None, None, (39, 2, 4), (46, 3, 4), (27, 2, 2), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [None, None, None, (24, 5, 4), (24, 4, 4), (30, 2, 4), (49, 2, 3), (35, 3, 5), None, (22, 6, 4), (19, 6, 5), (23, 8, 6), None, (30, 3, 3), None, (45, 4, 5), (39, 5, 6), (28, 3, 3), (32, 4, 4), (25, 5, 5), (24, 4, 5), (31, 3, 4), None, None, None, None, None, None, None, None, (42, 3, 4), (40, 3, 4), (26, 4, 5), (33, 3, 4), (24, 3, 4), (27, 3, 3), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
]
