#!/usr/bin/env python3
"""Turns the X11 5x7 BDF into the kit's own glyph table.

The BDF is the source of truth for the shapes; this writes them out as Swift
so the kit needs no bundle, no parser and no I/O to draw a word — the table
is compiled in, and a face drawing on a background thread touches nothing.

Bit convention is the kit's, not the BDF's. A BDF row packs its columns from
the most significant bit down (bit 7 is the leftmost of a 5-wide glyph); the
kit's canvas paints `bits & (1 << column)` at `cursor + column`, so bit 0 is
the LEFTMOST column. Each row is reversed on the way out.

    ./Scripts/MakeFontTable.py Scripts/font5x7-cyrillic.bdf \
        Sources/PixbarKit/Ulanzi/X11Glyphs.swift
"""

import sys
from pathlib import Path

CELL_WIDTH = 5
CELL_HEIGHT = 7

# What each codepoint is written as in a Swift character literal. Everything
# else goes through as itself.
ESCAPES = {
    0x22: '\\"',
    0x5C: "\\\\",
}


# Marks the BDF does not carry, drawn here in the same cell and the same bit
# order. The degree sign is not optional — every weather face draws one — and
# Ё/ё are the two letters the X11 Cyrillic block leaves out. Rows are written
# left-to-right as art and converted below, so what is in the source is the
# shape rather than a number nobody can read.
EXTRA_ART = {
    "°": [".##..", "#..#.", ".##..", ".....", ".....", ".....", "....."],
    # Е with its two dots, the body dropped one row to make room for them.
    "Ё": ["#.#..", "####.", "#....", "###..", "#....", "#....", "####."],
    # е is an x-height letter, so its dots sit on the empty top row.
    "ё": ["#.#..", ".....", ".##..", "#.##.", "##...", ".##..", "....."],
}


def art_rows(art):
    """Art written left-to-right, in the kit's bit-0-is-leftmost packing."""
    rows = []
    for line in art:
        bits = 0
        for column, mark in enumerate(line[:CELL_WIDTH]):
            if mark == "#":
                bits |= 1 << column
        rows.append(bits)
    return rows


def parse(bdf_text):
    """Every glyph in the file as (codepoint, [row bits, top first])."""
    glyphs = []
    encoding = None
    bbx = None
    rows = None
    for line in bdf_text.splitlines():
        line = line.strip()
        if line.startswith("ENCODING "):
            encoding = int(line.split()[1])
        elif line.startswith("BBX "):
            bbx = [int(part) for part in line.split()[1:]]
        elif line == "BITMAP":
            rows = []
        elif line == "ENDCHAR":
            if encoding is not None and encoding >= 0 and rows is not None:
                glyphs.append((encoding, bbx, rows))
            encoding, bbx, rows = None, None, None
        elif rows is not None and line:
            rows.append(int(line, 16))
    return glyphs


def kit_rows(bbx, rows):
    """The BDF's rows in the kit's bit order, padded to the fixed cell."""
    width, height = bbx[0], bbx[1]
    if (width, height) != (CELL_WIDTH, CELL_HEIGHT):
        raise SystemExit(f"glyph box {width}x{height} is not the {CELL_WIDTH}x{CELL_HEIGHT} cell")
    out = []
    for value in rows:
        # A BDF row is byte-aligned with the leftmost column at bit 7.
        bits = 0
        for column in range(CELL_WIDTH):
            if value & (1 << (7 - column)):
                bits |= 1 << column
        out.append(bits)
    while len(out) < CELL_HEIGHT:
        out.append(0)
    return out[:CELL_HEIGHT]


def literal(codepoint):
    if codepoint in ESCAPES:
        return ESCAPES[codepoint]
    character = chr(codepoint)
    if codepoint < 0x20 or codepoint == 0x7F:
        return f"\\u{{{codepoint:X}}}"
    return character


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    source, destination = Path(sys.argv[1]), Path(sys.argv[2])
    glyphs = parse(source.read_text(encoding="utf-8"))
    lines = [
        "// GENERATED by Scripts/MakeFontTable.py from Scripts/font5x7-cyrillic.bdf.",
        "// Do not edit by hand — edit the BDF and re-run the generator.",
        "//",
        "// The X11 \"Misc Fixed\" 5×7 face, public domain. Latin, digits, the",
        "// punctuation a face can draw, and the Cyrillic alphabet — the set the",
        "// live TC002 demo proved on 2026-09-21.",
        "//",
        "// Rows are top-first, one byte per row, low 5 bits = left-to-right",
        "// (bit 0 is the leftmost column) — the canvas's own convention.",
        "",
        "extension PixelFont {",
        f"    static let x11Glyphs: [Character: [UInt8]] = [",
    ]
    seen = set()
    for codepoint, bbx, rows in sorted(glyphs):
        if codepoint in seen:
            continue
        seen.add(codepoint)
        bits = kit_rows(bbx, rows)
        packed = ", ".join(f"0b{value:05b}" for value in bits)
        lines.append(f'        "{literal(codepoint)}": [{packed}],')
    lines.append("        // Drawn here rather than read from the BDF, which carries none of")
    lines.append("        // the three: the degree sign every weather face needs, and the two")
    lines.append("        // letters the X11 Cyrillic block leaves out.")
    for character, art in EXTRA_ART.items():
        packed = ", ".join(f"0b{value:05b}" for value in art_rows(art))
        lines.append(f'        "{character}": [{packed}],')
    lines.append("    ]")
    lines.append("}")
    lines.append("")
    destination.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(seen) + len(EXTRA_ART)} glyphs → {destination}")


if __name__ == "__main__":
    main()
